class Food {
  static final getData = [
    {
      'id': 0,
      'name': "Onion",
      'price': 20,
      'farmer': "Muthu",
      'place': 'Iyyappanthangal',
      'photo': 'assets/onion.png',
      'phnum': '9962386857',
      'color': 0xffF7DFB9,
    },
    {
      'id': 1,
      'name': "Tomato",
      'price': 15,
      'farmer': "Balaji",
      'place': 'Porur',
      'photo': 'assets/tomatoNew.png',
      'phnum': '9791113859',
      'color': 0xffC4D4A3,
    },
    {
      'id': 2,
      'name': "Cucumber",
      'price': 15,
      'farmer': "Balaji",
      'place': 'Porur',
      'photo': 'assets/cucumberNew.png',
      'phnum': '9791113859',
      'color': 0xffF6E475,
    },
    {
      'id': 3,
      'name': "Potato",
      'price': 30,
      'farmer': "Kumar",
      'place': 'Poonamallee',
      'photo': 'assets/potatoNew.png',
      'phnum': '9758624765',
      'color': 0xffFFC498,
    },
    {
      'id': 4,
      'name': "Mango",
      'price': 45,
      'farmer': "Kumar",
      'place': 'Poonamallee',
      'photo': 'assets/mango.png',
      'phnum': '9758624765',
      'color': 0xffF0AEAF,
    },
    {
      'id': 5,
      'name': "Beans",
      'price': 35,
      'farmer': "Muthu",
      'place': 'Iyyappanthangal',
      'photo': 'assets/beans.png',
      'phnum': '9962386857',
      'color': 0xffC4D4A3,
    },
    {
      'id': 6,
      'name': "Corn",
      'price': 15,
      'farmer': "Balaji",
      'place': 'Porur',
      'photo': 'assets/corn.png',
      'phnum': '9791113859',
      'color': 0xffF6E475,
    },
    {
      'id': 7,
      'name': "Papaya",
      'price': 45,
      'farmer': "Prabha",
      'place': 'Valasaravakkam',
      'photo': 'assets/strawberry.png',
      'phnum': '9791113859',
      'color': 0xffFFC498,
    },
    {
      'id': 8,
      'name': "Carrot",
      'price': 30,
      'farmer': "Kumar",
      'place': 'Poonamallee',
      'photo': 'assets/carrot.png',
      'phnum': '9758624765',
      'color': 0xffF0AEAF,
    },
    {
      'id': 9,
      'name': "Brinjal",
      'price': "₹45/kg",
      'farmer': "vasa",
      'place': 'Noombul',
      'photo': 'assets/brinjal.png',
      'phnum': '9758624526',
      'color': 0xffF7DFB9,
    },
  ];
}
